[package]
name = "craft-shell"
version = "0.1.0"
authors = ["Codecrafters <hello@codecrafters.io>"]
edition = "2024"
rust-version = "1.91"

[lib]
name = "shlib"
path = "src/lib.rs"

[dependencies]
rustyline = "17.0.2"
is_executable = "1.0.5"
